// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Joke struct {
	ID        int32              `json:"id"`
	Setup     string             `json:"setup"`
	Punchline string             `json:"punchline"`
	Category  pgtype.Text        `json:"category"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type JokeTag struct {
	JokeID    int32              `json:"joke_id"`
	TagID     int32              `json:"tag_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Tag struct {
	ID        int32              `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
