-- Seed data: 100 dad jokes across various categories
INSERT INTO jokes (setup, punchline, category) VALUES
-- General dad jokes
('Why don''t scientists trust atoms?', 'Because they make up everything!', 'science'),
('What do you call a fake noodle?', 'An impasta!', 'food'),
('Why did the scarecrow win an award?', 'Because he was outstanding in his field!', 'general'),
('I used to hate facial hair...', 'but then it grew on me.', 'general'),
('Why don''t eggs tell jokes?', 'They''d crack each other up!', 'food'),
('What do you call a can opener that doesn''t work?', 'A can''t opener!', 'general'),
('I''m reading a book about anti-gravity.', 'It''s impossible to put down!', 'science'),
('Did you hear about the restaurant on the moon?', 'Great food, no atmosphere.', 'food'),
('Why did the coffee file a police report?', 'It got mugged!', 'food'),
('What do you call a bear with no teeth?', 'A gummy bear!', 'animals'),

-- Food jokes
('What did the grape say when it got stepped on?', 'Nothing, it just let out a little wine!', 'food'),
('Why did the tomato turn red?', 'Because it saw the salad dressing!', 'food'),
('What do you call cheese that isn''t yours?', 'Nacho cheese!', 'food'),
('Why did the cookie go to the doctor?', 'Because it felt crumbly!', 'food'),
('What''s orange and sounds like a parrot?', 'A carrot!', 'food'),
('Why don''t oysters donate to charity?', 'Because they are shellfish!', 'food'),
('What do you call a sad strawberry?', 'A blueberry!', 'food'),
('Why did the banana go to the doctor?', 'Because it wasn''t peeling well!', 'food'),
('What do you call a sleeping pizza?', 'A piZZZa!', 'food'),
('Why did the mushroom go to the party?', 'Because he was a fungi!', 'food'),

-- Animal jokes
('What do you call a fish wearing a bowtie?', 'Sofishticated!', 'animals'),
('Why don''t elephants use computers?', 'They''re afraid of the mouse!', 'animals'),
('What do you call a pile of cats?', 'A meowtain!', 'animals'),
('Why do cows have hooves instead of feet?', 'Because they lactose!', 'animals'),
('What do you call a dog magician?', 'A labracadabrador!', 'animals'),
('Why don''t ants get sick?', 'Because they have little anty-bodies!', 'animals'),
('What do you call a sleeping bull?', 'A bulldozer!', 'animals'),
('Why do seagulls fly over the sea?', 'Because if they flew over the bay, they''d be bagels!', 'animals'),
('What do you call a bear in the rain?', 'A drizzly bear!', 'animals'),
('Why don''t crabs give to charity?', 'Because they''re shellfish!', 'animals'),

-- Science & Technology jokes
('Why can''t you trust an atom?', 'They make up literally everything!', 'science'),
('What did one DNA strand say to the other?', 'Do these genes make me look fat?', 'science'),
('Why did the physicist go to the beach?', 'To work on his tan-gent!', 'science'),
('What''s a computer''s favorite snack?', 'Microchips!', 'technology'),
('Why was the math book sad?', 'Because it had too many problems!', 'science'),
('What do you call a computer that sings?', 'A Dell!', 'technology'),
('Why did the robot go on a diet?', 'He had too many bytes!', 'technology'),
('What''s the best thing about Switzerland?', 'I don''t know, but the flag is a big plus!', 'general'),
('Parallel lines have so much in common.', 'It''s a shame they''ll never meet.', 'science'),
('Why do programmers prefer dark mode?', 'Because light attracts bugs!', 'technology'),

-- Sports jokes
('Why did the golfer bring two pairs of pants?', 'In case he got a hole in one!', 'sports'),
('Why can''t basketball players go on vacation?', 'They would get called for traveling!', 'sports'),
('Why did the soccer player bring string to the game?', 'So he could tie the score!', 'sports'),
('What do you call a boomerang that doesn''t come back?', 'A stick!', 'sports'),
('Why was Cinderella so bad at soccer?', 'Because she kept running away from the ball!', 'sports'),
('Why don''t tennis players ever get married?', 'Because love means nothing to them!', 'sports'),
('What do you call a snowman with a six-pack?', 'An abdominal snowman!', 'sports'),
('Why did the bicycle fall over?', 'Because it was two-tired!', 'sports'),
('What lights up a soccer stadium?', 'A soccer match!', 'sports'),
('Why don''t basketball players ever get hot?', 'Because they have so many fans!', 'sports'),

-- Dad jokes about being a dad
('I''m on a seafood diet.', 'I see food and I eat it!', 'dad'),
('What time did the man go to the dentist?', 'Tooth hurt-y!', 'dad'),
('I told my wife she was drawing her eyebrows too high.', 'She looked surprised!', 'dad'),
('What''s the best way to watch a fly fishing tournament?', 'Live stream!', 'dad'),
('Why did the invisible man turn down the job offer?', 'He couldn''t see himself doing it!', 'dad'),
('I only know 25 letters of the alphabet.', 'I don''t know y!', 'dad'),
('What did the zero say to the eight?', 'Nice belt!', 'dad'),
('Why do fathers take an extra pair of socks when they golf?', 'In case they get a hole in one!', 'dad'),
('I used to play piano by ear...', 'but now I use my hands!', 'dad'),
('What do you call a factory that makes okay products?', 'A satisfactory!', 'dad'),

-- More general jokes
('What do you call a parade of rabbits hopping backwards?', 'A receding hare-line!', 'animals'),
('Why don''t skeletons fight each other?', 'They don''t have the guts!', 'general'),
('What did one wall say to the other?', 'I''ll meet you at the corner!', 'general'),
('Why did the stadium get hot after the game?', 'All the fans left!', 'sports'),
('What do you call a man with a rubber toe?', 'Roberto!', 'general'),
('Why did the picture go to jail?', 'Because it was framed!', 'general'),
('What do you call a belt made of watches?', 'A waist of time!', 'general'),
('Why don''t some couples go to the gym?', 'Because some relationships don''t work out!', 'general'),
('What did the ocean say to the beach?', 'Nothing, it just waved!', 'general'),
('Why did the hipster burn his mouth?', 'He drank his coffee before it was cool!', 'general'),

-- Technology jokes
('Why did the smartphone need glasses?', 'It lost all its contacts!', 'technology'),
('What do you call a computer floating in the ocean?', 'A Dell Rolling in the Deep!', 'technology'),
('Why was the computer cold?', 'It left its Windows open!', 'technology'),
('What do you get when you cross a computer with an elephant?', 'Lots of memory!', 'technology'),
('Why did the PowerPoint presentation cross the road?', 'To get to the other slide!', 'technology'),
('What''s a programmer''s favorite hangout place?', 'Foo Bar!', 'technology'),
('Why do Java developers wear glasses?', 'Because they can''t C#!', 'technology'),
('What did the router say to the doctor?', 'It hurts when IP!', 'technology'),
('Why was the JavaScript developer sad?', 'Because he didn''t Node how to Express himself!', 'technology'),
('What do you call a programmer from Finland?', 'Nerdic!', 'technology'),

-- Science jokes
('What did the thermometer say to the graduated cylinder?', 'You may have graduated, but I have more degrees!', 'science'),
('Why are chemists excellent for solving problems?', 'They have all the solutions!', 'science'),
('What do you call an educated tube?', 'A graduated cylinder!', 'science'),
('Why did the germ cross the microscope?', 'To get to the other slide!', 'science'),
('What do you do with a sick chemist?', 'If you can''t helium, and you can''t curium, you might as well barium!', 'science'),
('What is a physicist''s favorite food?', 'Fission chips!', 'science'),
('Why can''t you trust atoms?', 'They make up everything, even this joke!', 'science'),
('What did the biologist wear to impress?', 'Designer genes!', 'science'),
('Why do biologists look forward to casual Fridays?', 'They''re allowed to wear genes to work!', 'science'),
('What did one quantum physicist say when he wanted to fight another quantum physicist?', 'Let me atom!', 'science');
